missing token rights

diff --git a/.github/workflows/provenance.yaml b/.github/workflows/provenance.yaml
--- a/.github/workflows/provenance.yaml
+++ b/.github/workflows/provenance.yaml
@@ -1,4 +1,4 @@
-name: slsa_provenance_verification
+name: slsa_provenance_creation
 
 on:
   workflow_call:
@@ -20,23 +20,54 @@ on:
         required: false
         type: string
         default: 'v1.13.1'
+      builder_version:
+        description: 'The version of SLSA provenance builder to use'
+        required: false
+        type: string
+        default: 'v1.4.0'
+      predicate_file:
+        description: 'The name of the predicate file to create'
+        required: false
+        type: string
+        default: 'predicate.json'
 
 permissions:
   contents: read
 
+
 jobs:
-  verify:
+  provenance:
     runs-on: ubuntu-latest
     needs:
     - build
-    - provenance
     permissions:
       actions: read
       id-token: write
+      packages: write
     steps:
 
-    - name: Checkout Code
-      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0
+    - name: Install SLSA Provenance Builder
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        set -euo pipefail
+        gh -R slsa-framework/slsa-github-generator \
+          release download ${{ input.builder_version }} -p $BUILDER
+        chmod ug+x $BUILDER
+        COMPUTED_HASH=$(sha256sum $BUILDER | cut -d ' ' -f1)
+        EXPECTED_HASH="893dc33e91ed5200d2932832c99e1b28011cecb836728f9604a571f71cf4c1b4"
+        if [[ "$EXPECTED_HASH" != "$COMPUTED_HASH" ]];then
+            echo "error: expected $EXPECTED_HASH, computed $COMPUTED_HASH"
+            exit 1
+        fi
+
+    - name: Create Predicate
+      env:
+        GITHUB_CONTEXT: "${{ toJSON(github) }}"
+        COSIGN_EXPERIMENTAL: 1
+      run: |
+        set -euo pipefail
+        "./$BUILDER" generate --predicate ${{ input.predicate_file }}
 
     - id: auth
       name: Auth GCP
@@ -57,12 +88,14 @@ jobs:
         cosign version
         cosign login ${{ env.REG_URI }} --username=oauth2accesstoken --password=${{ steps.auth.outputs.access_token }}
 
-    - name: Verify Image SLSA Provenance
+    - name: Create SLSA Provenance
       env:
+        GITHUB_CONTEXT: "${{ toJSON(github) }}"
         COSIGN_EXPERIMENTAL: 1
       run: |
         set -euo pipefail
-        cosign verify-attestation \
+        cosign attest \
+          --predicate ${{ input.predicate_file }} \
           --type slsaprovenance \
-          --policy policy/provenance.cue \
+          --force \
           ${{ input.image_digest }}
